### ISSUE TITLE
登录模块提示系统异常

### ISSUE THREAD

**Issue by RavenCri** [jerryshell/cpdaily-api#1]
账号密码都配置了，使用login模块提示异常，请问应该是什么问题呢？
```
{"errCode":2003,"errMsg":"系统异常，请稍后重试","data":{"personId":"","userId":"","openId":"","name":"","tenantId":"","mobile":"","userType":"STUDENT","status":"","authStatus":"","deviceStatus":"noexception","deviceExceptionMsg":"","tgcStatus":"","tgc":"","sessionToken":"","yibanStatus":"","yibanToken":"","yibanMainDomain":"","auditRole":"","firstLogin":false}}
---sessionToken
```

**Comment by jerryshell** [comment]
请问你的学校的 iap 地址是 `https://<学校名字>.cpdaily.com/iap'` 这种格式的吗？

因为我只测试了我自己的学校，其他学校的不知道会有什么问题。。。

**Comment by RavenCri** [comment]
> 请问你的学校的iap地址是`https://<学校名字>.cpdaily.com/iap'`这种格式的吗？
> 
> 因为我只测试了我自己的学校，其他学校的不知道会有什么问题。。。

是的，我使用抓包，抓到了这个网站。https://hfuu.cpdaily.com/iap/login?service=https%3A%2F%2Fhfuu.cpdaily.com%2Fportal%2Flogin。因为我太菜了，剩下的不会搞了，想学习大佬如何做的。但是登录不进去

**Comment by RavenCri** [comment]
我看别人说的，金智改了后端的验证，您现在还可以正常使用吗

**Comment by jerryshell** [comment]
![image](https://i.loli.net/2020/04/03/jx48h9UKWS6glbL.png)

我这里到最后一步会提示 `抱歉，这不是小i认识的那台手机了，出于安全，我们将发出一条通知短信。如果是您本人操作，请忽略。`

这里要改 `config.py` 里的 `cpdaily_info` 变量来适配以前登录过的手机才行

或者去适配他的短信接口

但是最近重装系统了，抓包什么的环境也懒得弄所以还在一直拖着。。。

**Comment by jerryshell** [comment]
今日校园的后端主要是通过 `deviceId` 区别每个手机

如果 `deviceId` 和以前登录的不一样就会触发短信校验

~~现在的难点是每个手机的 `deviceId` 生成的位置都不一样，找起来有点麻烦~~

更新：其实 `deviceId` 就在 `/storage/emulated/0/wismcp/device/device_id.json` 里面，位置是固定的（

**Comment by RavenCri** [comment]
谢谢大佬了。大佬能分享下你的研究思路吗。我很佩服你们这些会抓包的大佬。想学习学习。或者有博客地址吗？

**Comment by jerryshell** [comment]
参考的抓包教程主要是这个：

http://book.crifan.com/books/app_capture_package_tool_charles/website

不过你既然都能拿到学校的地址了，应该也不需要这个了

主要思路其实就是一步一步跟，用耐心慢慢耗。。。

博客原来有写，但是还是觉得自己的积累太少，就不误人子弟了，后来又关了

`cpdaily_info` 的编码器我今天研究一下争取做出来吧 😄

**Comment by jerryshell** [comment]
Hi，@clothesack

我已经完成了`cpdaily_info` 的编码器

你现在重新按照新的操作说明试试看能正常登录了没？

**Comment by clothesack** [comment]
大佬，我试了。当我使用Loging模块获取sessionToken时，提示系统异常。上午就是这样，现在还是这样。不知道什么原因。![image](https://user-images.githubusercontent.com/39519250/78361685-64f89b00-75eb-11ea-8bd9-93e12be28fc4.png)

**Comment by jerryshell** [comment]
我去翻了一下 `tenant_list.json` 发现你们学校的 id 有点不一样。。。

`config.py` 的 `tenant_id` 你设置成了 `hfuu` 还是 `fef8d342-799a-44db-9121-f67eb6099dee` 呢？

`fef8d342-799a-44db-9121-f67eb6099dee` 才是正确的设置

**Comment by RavenCri** [comment]
解决问题了。感谢大佬的指导。

**Comment by jerryshell** [comment]
对了，最好把上面那个截图删了哦，可能会泄漏敏感信息
