### ISSUE TITLE
大佬，能否提供下您编写encoder模块的思路

### ISSUE THREAD

**Issue by RavenCri** [jerryshell/cpdaily-api#2]
在 阶段 3：编码 iap，获取 ticket时，看到大佬使用了自己编写了函数编码生成ticket。
如果方便的话，大佬能简单说下，破解的大致思路是怎样的。是不是需要逆向破解app，查看源代码呢？

![image](https://user-images.githubusercontent.com/39519250/78467039-3558a880-773b-11ea-9f40-40d7374291c2.png)

**Comment by jerryshell** [comment]
Hi，@clothesack

这部分我确实是通过逆向 APP 得到的，因为抓包是抓不出来的

使用的逆向工具是 jadx：https://github.com/skylot/jadx

逆向的 APP 版本是 v8.0.8，其他的版本不知道能不能反编译成功，手机乐园可以下载旧版本：https://soft.shouji.com.cn/down/1549214.html

**Comment by RavenCri** [comment]
感谢大佬的指引。thanks!

**Comment by jerryshell** [comment]
对了，当你进行 login 调试的时候最好不要手工进行 iap 到 ticket 的编码

iap 到 ticket 的编码服务器那边大概只给客户端 6 秒的时间，除非你的手速很快，否则很容易超时，使用超时的 ticket 去登录就会显示系统异常

我以前调试的时候，都是单独写编码器然后手工复制粘贴进行编码，结果每次都系统异常，这一点坑了我很久。。。

**Comment by RavenCri** [comment]
谢谢大佬提醒。
再问问您，这么多class，如何快速找到登录模块，或者有什么技巧吗？我就是想看看源代码怎么找，学习一下经验。。我看到这个APP的源码都加密了，反编译的源码有部分还是jvm 指令。大佬有精力可以当个up主，科普下这些技巧，让我等小白学习学习

![image](https://user-images.githubusercontent.com/39519250/78468015-bfa60a00-7745-11ea-97de-f6ecf0cde7cb.png)

**Comment by jerryshell** [comment]
我的主要切入点还是依赖 jadx 的文本搜索功能啦～

比如通过抓包分析之后，我们都知道登录的过程中是会请求 `https://www.cpdaily.com/v6/auth/campus/cas/login` 这个地址的

既然要请求这个地址，那么登录模块就一定会在某个地方使用这个字符串来拼接请求

顺着这个思路，我们可以搜索先 `cas/login` 这个字符串，其实能搜出来的类没几个

多找找你很快就能发现登录的入口是 `com.wisorg.wisedu.campus.activity.IdsLoginActivity`

至于你说的反编译之后还有 JVM 指令的问题，或许是反编译工具的问题？我这边反编译出来的源码都挺正常的，甚至变量名都能很好的还原回来，或许你可以考虑一下用我上面提到的 jadx 试试看。。。

靠破解 APP 来当 UP 我个人感觉是做不到啦～毕竟这里属于法律的灰色地带，说不定哪天就进去蹲局子了（

我个人的观点是：逆向的基础是正向。做 APP 逆向之前首先自己本身已经了积累了开发 APP 的经验是挺重要的。同时从「破解者」和「开发者」两个角度去思考问题或许能收获更多的想法。

**Comment by jerryshell** [comment]
Close inactive issue.
