### ISSUE TITLE
我这个是什么问题呀？

### ISSUE THREAD

**Issue by Aimeryai** [jerryshell/cpdaily-api#4]
出现问题了！HTTPSConnectionPool(host='www.cpdaily.com', port=443): Max retries exceeded with url: /v6/config/guest/tenant/list (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0eaeb58358>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by jerryshell** [comment]
今日校园换了二级域名，这个项目已经停止开发，详情见：https://github.com/jerryshell/cpdaily-api/issues/3

**Comment by jerryshell** [comment]
Close inactive issue.
